#ifndef DEFINE_H
#define DEFINE_H

#define MAIN_WINDOW_ICON "C:/Users/Phoug/Pictures/Icon/morty_icon"

#define NUMBERS_OF_LAB_FRAMES 6

// lab01
#define LAB1_SCREEN_WEIGHT 600
#define LAB1_SCREEN_HEIGHT 520

#define TEXT_SIZE 20
#define LABEL_POS 0

#define CHARACTER_WEIGHT 120
#define CHARACTER_HEIGHT 164

#define BATTERY_TIME_LABEL_WIDTH 350
#define BATTERY_FIXED_HEIGHT 250
#define BATTERY_FIXED_WEIGHT 100
#define BATTERY_CHARHE_MIN 0
#define BATTERY_CHARGE_MAX 100

#define TIMER_VALUE 1000
#define BLINK_TIMER 500

#define LAYOUT_POS      10
#define INFO_LAYOUT_POS 0

#endif // DEFINE_H
